### ISSUE TITLE
Awesomebar broken after uninstall 

### ISSUE THREAD

**Issue by jeffgca** [mozilla/universal-search#225] opened 2016-05-16 23:36 UTC
I see this when I type something into the awesomebar after uninstalling this add-on:

TypeError: rows[0] is undefined
adjustHeight()
autocomplete.xml:1169
_invalidate/this._adjustHeightTimeout<()
autocomplete.xml:1116
autocomplete.xml:1169:19

**Comment by jeffgca** [comment] 2016-05-16 23:41
@nchapman @andymckay  - restarting a couple of times seems to have fixed this

**Comment by ianb** [comment] 2016-05-17 18:24
I've gotten this today as well.  In autocomplete.xml, `let rows = this.richlistbox.childNodes; let numRows = Math.min(this._matchCount, this.maxRows, rows.length);` – at first I wondered if the childNodes changed behind the back of the function, but that wouldn't explain the sticky brokenness.  So now I'm wondering if one of those other parameters to Math.min became negative.

**Comment by jaredhirsch** [comment] 2016-05-18 01:33
@canuckistani Was this observed after a nightly or dev edition version upgrade? There seems to be really weird behavior on thefirst restart after an update :-\

**Comment by ianb** [comment] 2016-05-18 15:00
FYI, I am running in Dev Edition, with a fresh install, with the add-on turned on (same exception message as @canuckistani)

**Comment by jaredhirsch** [comment] 2016-05-18 15:15
@ianb Awesome, I'll try on dev edition today. There was a similar issue (#164) on dev edition not too long ago, but it "went away" after a few days, which led me to think a buggy patch got yanked or a fix was uplifted (but I didn't check to be sure).

> I'm wondering if one of those other parameters to Math.min became negative.

There's a subtle issue with the matchCount getter that is difficult to reproduce consistently. This seems like another occurrence of that issue.

**Comment by jaredhirsch** [comment] 2016-05-20 18:17
The `matchCount` getter issue should be solved by #230 along with other mysterious nightly/dev edition breakage. Optimistically closing, as this should be fixed in the next update (early next week).

**Closed as completed by jaredhirsch** 2016-05-20 18:17 UTC
