### ISSUE TITLE
Restore the search box when disabling

### ISSUE THREAD

**Issue by birtles** [mozilla/universal-search#214] opened 2016-05-12 04:49 UTC
When disabling Universal Search, the separate search box is not restored. I need to go to Customize and re-add it manually. This is true even after restarting.

**Comment by jaredhirsch** [comment] 2016-05-12 17:26
@birtles do you also have tab center installed?

**Comment by jaredhirsch** [comment] 2016-05-12 18:12
Closing as a duplicate of #216. @birtles, please feel free to reopen if you feel this was duped in error.

**Closed as completed by jaredhirsch** 2016-05-12 18:12 UTC

**Comment by birtles** [comment] 2016-05-12 23:05
No, I don't although I did enable it previously.
