### ISSUE TITLE
Universal Search not letting me search with awesome bar

### ISSUE THREAD

**Issue by Work-Parker** [mozilla/universal-search#287] opened 2016-08-04 21:16 UTC
When trying URL's or anything in the awesomebar and hitting enter or the search button on it, nothing will happen. Only when disability Universal search will I be able to search something
- [ ] Operating system: windows 10
- [ ] Firefox build: nightly 51.0a1 (2016-08-04)

***_start of about:support information**_*
## Application Basics

Name: Firefox
Version: 51.0a1
Build ID: 20160804030441
Update Channel: nightly
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
OS: Windows_NT 10.0
Multiprocess Windows: 1/1 (Enabled by default)
Safe Mode: false
## Crash Reports for the Last 3 Days

Report ID: bp-c157eb6a-27c6-4fef-b06f-9cc852160803
Submitted: 24 hours ago

Report ID: bp-f82be0f5-17fd-4a48-9e22-3cde12160803
Submitted: 24 hours ago

All Crash Reports
## Extensions

Name: FlyWeb
Version: 1.0.0
Enabled: true
ID: flyweb@mozilla.org

Name: Multi-process staged rollout
Version: 1.0
Enabled: true
ID: e10srollout@mozilla.org

Name: No More 404s
Version: 1.5.3
Enabled: true
ID: wayback_machine@mozilla.org

Name: Pocket
Version: 1.0.4
Enabled: true
ID: firefox@getpocket.com

Name: Test Pilot
Version: 0.8.3-tag-2016-07-29
Enabled: true
ID: @testpilot-addon

Name: Web Compat
Version: 1.0
Enabled: true
ID: webcompat@mozilla.org

Name: uBlock Origin
Version: 1.8.0
Enabled: false
ID: uBlock0@raymondhill.net

Name: Universal Search
Version: 1.0.8
Enabled: false
ID: universal-search@mozilla.com
## Graphics

Features
Compositing: Direct3D 11
Asynchronous Pan/Zoom: wheel input enabled; touch input enabled
WebGL Renderer: Google Inc. -- ANGLE (NVIDIA Quadro NVS 160M Direct3D11 vs_4_0 ps_4_0)
WebGL2 Renderer: WebGL creation failed: \* Refused to create native OpenGL context because of blacklist entry: WEBGL_NATIVE_GL_OLD_NVIDIA \* Exhausted GL driver options.
Hardware H264 Decoding: No; Hardware video decoding disabled or blacklisted
Audio Backend: wasapi
Direct2D: true
DirectWrite: true (10.0.10586.494)
GPU #1
Active: Yes
Description: NVIDIA Quadro NVS 160M
Vendor ID: 0x10de
Device ID: 0x06eb
Driver Version: 9.18.13.4192
Driver Date: 10-13-2015
Drivers: nvd3dumx,nvwgf2umx,nvwgf2umx nvd3dum,nvwgf2um,nvwgf2um
Subsys ID: 024f1028
RAM: 256

Diagnostics
AzureCanvasAccelerated: 0
AzureCanvasBackend: direct2d 1.1
AzureContentBackend: direct2d 1.1
AzureFallbackCanvasBackend: cairo
## Important Modified Preferences

accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 4
browser.download.importedFromSqlite: true
browser.download.useDownloadDir: false
browser.places.smartBookmarksVersion: 8
browser.sessionstore.upgradeBackup.latestBuildID: 20160804030441
browser.startup.homepage_override.buildID: 20160804030441
browser.startup.homepage_override.mstone: 51.0a1
browser.tabs.crashReporting.email: parkerhasmail@protonmail.com
browser.tabs.crashReporting.emailMe: true
browser.tabs.crashReporting.includeURL: true
dom.apps.lastUpdate.buildID: 20160725030248
dom.apps.lastUpdate.mstone: 50.0a1
dom.apps.reset-permissions: true
dom.mozApps.used: true
extensions.lastAppVersion: 51.0a1
font.internaluseonly.changed: false
gfx.crash-guard.d3d11layers.appVersion: 45.2.0
gfx.crash-guard.d3d11layers.deviceID: 0x06eb
gfx.crash-guard.d3d11layers.driverVersion: 9.18.13.4192
gfx.crash-guard.d3d11layers.feature-d2d: true
gfx.crash-guard.d3d11layers.feature-d3d11: true
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.d3d9video: 2
gfx.direct3d.last_used_feature_level_idx: 1
media.benchmark.vp9.fps: 61
media.benchmark.vp9.versioncheck: 1
media.gmp-eme-adobe.abi: x86_64-msvc-x64
media.gmp-eme-adobe.lastUpdate: 1470081446
media.gmp-eme-adobe.version: 17
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1470081447
media.gmp-gmpopenh264.version: 1.5.3
media.gmp-manager.buildID: 20160804030441
media.gmp-manager.lastCheck: 1470324903
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.lastUpdate: 1469110883
media.gmp-widevinecdm.version: 1.4.8.866
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: true
network.cookie.cookieBehavior: 1
network.cookie.prefsMigrated: true
network.dns.disablePrefetch: true
network.http.pipelining.ssl: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1469805250
places.history.expiration.transient_current_max_pages: 122334
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
privacy.clearOnShutdown.cache: false
privacy.clearOnShutdown.downloads: false
privacy.clearOnShutdown.history: false
privacy.clearOnShutdown.offlineApps: true
privacy.cpd.cookies: false
privacy.sanitize.migrateClearSavedPwdsOnExit: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.sanitizeOnShutdown: true
privacy.trackingprotection.enabled: true
privacy.trackingprotection.introCount: 20
security.sandbox.content.tempDirSuffix: {511db220-75e5-40d8-8658-4f9b73cf1298}
security.ssl.errorReporting.automatic: true
security.tls.version.max: 1
security.tls.version.min: 0
services.sync.declinedEngines:
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1469111303
ui.osk.debug.keyboardDisplayReason: IKPOS: Touch screen not found.
## JavaScript

Incremental GC: true
## Accessibility

Activated: false
Prevent Accessibility: 0
## Library Versions

NSPR
Expected minimum version: 4.12
Version in use: 4.12

NSS
Expected minimum version: 3.26
Version in use: 3.26

NSSSMIME
Expected minimum version: 3.26
Version in use: 3.26

NSSSSL
Expected minimum version: 3.26
Version in use: 3.26

NSSUTIL
Expected minimum version: 3.26
Version in use: 3.26
## Experimental Features

***_end of about:support information**_*

**Comment by salmanulfarzy** [comment] 2016-08-05 06:53
Similar to #286. Also in OS X

**Comment by SoftVision-CosminMuntean** [comment] 2016-08-05 07:18
I can also reproduce this issue on the latest Nightly (51.0a1 - Build ID: 20160804030441) on Windows 7 x64. Considering the fact that this issue is not reproducible on Nightly (50.0a1), I have performed a regression.

This are the results:
- Pushlog: https://goo.gl/puqLi8

I think that this fix affected the Universal Search add-on.

See also #286.

**Comment by Work-Parker** [comment] 2016-08-05 13:36
So if this issue has been seen before, what can be do to fix the bug?

**Comment by ghost** [comment] 2016-08-05 15:54
Thanks for the detailed bug report.  I'm going to close this as a dupe of #286 .

**Closed as completed by ghost** 2016-08-05 15:54 UTC
