### ISSUE TITLE
Awesomebar results broken in the latest nightly with "this.mInput is null"

### ISSUE THREAD

**Issue by past** [mozilla/universal-search#138] opened 2016-04-09 18:06 UTC
I get this in the browser console:

```
TypeError: this.mInput is null autocomplete.xml:1140:11

get__matchCount() autocomplete.xml:1140
_invalidate() autocomplete.xml:1107
invalidate() autocomplete.xml:1097
Search.prototype.notifyResults() UnifiedComplete.js:1821
_addMatch() UnifiedComplete.js:1443
Search.prototype._onResultRow() UnifiedComplete.js:1360
bound () self-hosted
ConnectionData.prototype<._executeStatement/pending<.handleResult() Sqlite.jsm:763

```

I bet this is caused by the landing of [bug 1195054](https://bugzilla.mozilla.org/show_bug.cgi?id=1195054).

**Comment by chuckharmston** [comment] 2016-04-10 00:26
Thanks for the report, @past!

Does this actually prevent recommendation from showing, or is it an idle error in the console? We've been tracking it for some time in #29, but haven't noticed any undesired consequences so it hasn't been prioritized.

**Comment by past** [comment] 2016-04-10 08:19
It prevents all awesomebar results from appearing, not just the recommendation. This was just the first error in the console, it may be that the rest of them are more pertinent? I'm not in my computer at the moment to check this.

**Comment by jaredhirsch** [comment] 2016-04-11 21:11
@past Hi, the `this.mInput is null` error has been known for a while, and hasn't (in the past) prevented rendering of the popup contents. I'll look at nightly and try to reproduce. If you have other STR or other browser toolbox console error messages, those would be helpful.

**Comment by jaredhirsch** [comment] 2016-04-11 22:06
Unable to reproduce with these steps:
- open nightly
- create new profile
- install add-on

<img width="829" alt="screen shot 2016-04-11 at 3 04 02 pm" src="https://cloud.githubusercontent.com/assets/96396/14443845/b551bb82-fff6-11e5-82f2-11bd7da9b4ca.png">

**Comment by jaredhirsch** [comment] 2016-04-11 22:06
@nchapman mentioned seeing some weirdness when being upgraded to the new nightly awesomebar experience. I'll try that next.

**Comment by jaredhirsch** [comment] 2016-04-11 23:26
Aha! The plot thickens.

STR:
1. Start nightly, create a fresh profile in the profile picker
2. Install devprefs addon
3. Close nightly and "install" the search addon (I use a [proxy file](https://developer.mozilla.org/en-US/Add-ons/Setting_up_extension_development_environment#Firefox_extension_proxy_file), not a packaged XPI, for local development)
4. Reopen nightly
5. Usually the popup will work initially, then will stop working after the first time it closes (or disable and re-enable to trigger the bug).
6. Instead of a _single_ `this.mInput is null` error when Firefox initially opens, the error is shown for every result (up to 10x for a single letter):

<img width="939" alt="screen shot 2016-04-11 at 4 06 18 pm" src="https://cloud.githubusercontent.com/assets/96396/14445116/6acfebb6-ffff-11e5-988a-b801a7b7ade3.png">

**Comment by jaredhirsch** [comment] 2016-04-12 01:00
Last working nightly: 2016-04-05-03-02-14
First broken nightly: 2016-04-06-03-02-21

Tomorrow, I'll look at what landed in that window.

**Comment by jaredhirsch** [comment] 2016-04-12 22:58
https://bugzil.la/1181078 is the only awesomebar patch that landed on April 5, so that 1800-line diff contains the answer somewhere.

**Comment by jaredhirsch** [comment] 2016-04-12 23:44
Working on this first, because I really have no idea how long it'll take to figure out. Pessimistically setting to 'large' size.

**Comment by jaredhirsch** [comment] 2016-04-20 01:38
The problem is that we use a [`popuphiding` listener](https://github.com/mozilla/universal-search/blob/master/lib/ui/popup.js#L38-L40) to unset some state when the popup closes, but it overrides the XBL `popuphiding` listener. The XBL `popuphiding` handler [unsets `this.mPopupOpen`](https://dxr.mozilla.org/mozilla-central/source/toolkit/content/widgets/autocomplete.xml#990). This is important because, if `this.mPopupOpen` is left as `true`, then `this.mInput` won't be set [inside `_openAutocompletePopup`](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/urlbarBindings.xml#1346-1350).

I haven't been able to get a pointer to the XBL handler function, so the WIP branch fixes the bug by creating a synthetic `popuphiding` event, and firing it on the `gURLBar.popup`.

The WIP branch doesn't fix the case where the popup is first opened. If I manually set `gURLBar.popup.mPopupOpen = false` in the Browser Toolbox, I'm able to open, close, reopen the popup without any issues. If I don't manually set `mPopupOpen`, the bug still occurs: the popup opens once, containing just the recommendation, then won't reopen after it closes.

I need to figure out how to correctly initialize `mPopupOpen` or `mInput` or both, then we'll be good to land this fix.

**Closed as completed** 2016-04-21 16:00 UTC
