### ISSUE TITLE
Should suggest to search with all search engines

### ISSUE THREAD

**Issue by RenaultR42** [mozilla/universal-search#252] opened 2016-06-11 11:37 UTC
I think the new URL bar should propose to users to search with the keyword on each search engines enabled in settings.

Because without this possibility, it is very difficult to search with another search engine, only the default was easily accessible.  I think all enabled search engines should be accessible by this way.

**Comment by chuckharmston** [comment] 2016-07-06 15:52
Thanks for the report!

Closing this as a duplicate of https://github.com/mozilla/universal-search/issues/259, which has an interface suggestion.

**Closed as completed by chuckharmston** 2016-07-06 15:52 UTC
