### ISSUE TITLE
Poor results for pinterest

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#172] opened 2016-05-02 22:18 UTC
Found in 1.0.2

---
### Steps to reproduce:
1. Install Universal Search via TestPilot.
2. Type "pinterest" in the address bar.
### Actual results:

I'm not getting a favicon or preview image for pinterest [or nilke.com].

![new_tab_and_new_issue_ _mozilla_universal-search_and_add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14969662/668f0a9e-1078-11e6-9be3-4b821be969dd.png)

Not sure if this is specific to pinterest.com (which has a history with Embed.ly -- http://blog.embed.ly/post/119462317541/pinterest) or if this is just a caching/timing issue.

I'm seeing similar results w/ nike.com using Embed.ly extract API: http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fnike.com

![new_tab_and_new_issue_ _mozilla_universal-search_and_join_us__in_vidyo__for_activity_stream_user_research_interviews_-_pdehaan_mozilla_com_-_mozilla_mail](https://cloud.githubusercontent.com/assets/557895/14969765/f6a17c98-1078-11e6-854e-5515bab6dfb6.png)

For Activity-Stream, we're currently using Nick Chapman's [**tippy-top-sites**](https://github.com/nchapman/tippy-top-sites) project to give us some better images, background colors, etc.

**Comment by jaredhirsch** [comment] 2016-05-03 18:55
Hey @pdehaan, thanks for filing this bug. The colored letterbox is the fallback that is used if no image is available. The default globe favicon is the fallback that is used if no favicon is available. This is working as intended, closing.

**Closed as completed by jaredhirsch** 2016-05-03 18:55 UTC

**Comment by chuckharmston** [comment] 2016-05-03 19:18
This also gets better with the fixes for https://github.com/mozilla/universal-search-recommendation/issues/117 and https://github.com/mozilla/universal-search/issues/165:

![screen shot 2016-05-03 at 1 17 49 pm](https://cloud.githubusercontent.com/assets/23885/14995331/7929d6de-1131-11e6-9565-e7cf99b979bd.png)
