### ISSUE TITLE
Can't disable universal search

### ISSUE THREAD

**Issue by fabiorios** [mozilla/universal-search#258] opened 2016-07-05 23:20 UTC
Needed to temporarily remove it. I disabled it, but the single address bar remains. Running Windows10
![universal search](https://cloud.githubusercontent.com/assets/19597198/16602867/5797e0a2-42cc-11e6-9d6e-f9ef05cb93e4.JPG)

**Comment by chuckharmston** [comment] 2016-07-06 15:22
Thanks for the report!

This is a duplicate of https://github.com/mozilla/universal-search/issues/242, closing in favor of that bug.

**Closed as completed by chuckharmston** 2016-07-06 15:22 UTC
