### ISSUE TITLE
The latest or the first suggestions from the list is not focused while navigating from keyboard arrows

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#299] opened 2016-08-19 13:40 UTC
[Affected versions]:
- Nightly 51.0a1
- Universal Search 1.0.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Universal Search add-on (v1.0.8) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and enter a keyword on the Awesome Bar.
2. After the suggestions list is displayed, navigate through all the suggestion from the displayed list using the "down" or "up" arrow keys.

[Expected result]:
- All the elements from the suggestions list are correctly focused while navigating using the "up" and "down" arrows keys.

[Actual result]:
- Using the "down" arrow key, the latest suggestion from the list is not focused, while the first is.
- Using the "up" arrow key, the recommended website and the first suggestion from the list is not focused, while the last is.

[Notes]:
- Added a screen recording with the issue:  https://goo.gl/Ac50yb

**Comment by jaredhirsch** [comment] 2016-08-25 22:09
dupe of #292, closing

**Closed as completed by jaredhirsch** 2016-08-25 22:09 UTC
