### ISSUE TITLE
Universal Search add-on stuck on "Enabling"

### ISSUE THREAD

**Issue by anilatluri** [mozilla/universal-search#220] opened 2016-05-13 06:32 UTC
Windows 10 (upgrade from W7)
"Enabling "
Continuous loop for more than couple of hours.

**Comment by chuckharmston** [comment] 2016-05-13 14:22
Thanks for the report! I believe this is a duplicate of https://github.com/mozilla/testpilot/issues/802, feel free to re-open if you disagree.

**Closed as completed** 2016-05-13 15:48 UTC
