### ISSUE TITLE
universal search won't enable

### ISSUE THREAD

**Issue by nZpUhsX** [mozilla/universal-search#235] opened 2016-05-24 18:24 UTC
i have tried enabling universal search a few times now, but it just doesn't seem to want to do so. i have restarted firefox and that didn't help. i am running 46.0.1. any thoughts as to what i might be doing wrong? thanks for your help :)

**Comment by chuckharmston** [comment] 2016-07-06 15:17
Thanks for the report!

I believe this is a Test Pilot problem; in fact, a duplicate of https://github.com/mozilla/testpilot/issues/963. Closing in favor of that issue.

**Closed as completed by chuckharmston** 2016-07-06 15:17 UTC
