### ISSUE TITLE
Disabling and Enabling the extension in the same session doesn't work

### ISSUE THREAD

**Issue by glandium** [mozilla/universal-search#219] opened 2016-05-12 23:13 UTC
I had a weird problem with the awesomebar, which I wondered whether it was related to universal search or not (for the same query, it would show no results at all in one window, and normal results in another window), so I disabled Universal Search, and that didn't fix it. So I re-enabled Universal Search, and that didn't do anything: still a separate search box, and no recommendations. (Which leads me to believe it might not have disabled itself properly too, so nothing conclusive to say Universal Search is not involved in my original problem)

**Comment by jaredhirsch** [comment] 2016-05-20 03:22
@glandium Hey, did you have Tab Center installed when you tried to disable / re-enable? There are known issues with Tab Center breaking the code that Universal Search uses to clean up after itself.

**Comment by glandium** [comment] 2016-05-20 04:19
I'm about 90% sure I had Tab Center enabled.

**Comment by jaredhirsch** [comment] 2016-05-20 18:11
@glandium Good news: there's a known issue with Tab Center breaking the customize code that Universal Search uses to remove and restore the separate search bar: https://github.com/bwinton/VerticalTabs/issues/168

That issue's fixed, and should hopefully go away next time the Tab Center add-on is released (I believe we'll be doing releases early next week).

Closing as a dupe of https://github.com/bwinton/VerticalTabs/issues/168.

**Closed as completed by jaredhirsch** 2016-05-20 18:11 UTC
