### ISSUE TITLE
Enabling Universal Search experiment prevents to access any webpage in address bar

### ISSUE THREAD

**Issue by khalid32** [mozilla/universal-search#290] opened 2016-08-06 04:42 UTC
[Affected Version]:

```
Nightly 51.0a1
```

[Affected Platforms]:

```
Ubuntu 16.04, Linux 4.4.0-31-generic
```

[Prerequisites]:

```
Test Pilot is installed from https://testpilot.stage.mozaws.net/
```

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net/experiments
2. Navigate to Enable the "Universal Search" experiment page.
3. Chose to enable universal search.
4. Then go to new tab, type any URL of a web-page in address bar and press ENTER

[Expected Result]:
The experiment is successfully enabled and able to show the web page of given URL

[Actual Result]:
The experiment is successfully enabled but no response showed in the address bar

[Notes]:
    This issue only occurs when enabling "Universal Search" experiment.

**Comment by lissyx** [comment] 2016-08-06 14:41
dupe of #286

**Closed as completed** 2016-08-10 00:21 UTC
