### ISSUE TITLE
When enter customize, I can't modify the bar

### ISSUE THREAD

**Issue by Noitidart** [mozilla/universal-search#205] opened 2016-05-11 03:37 UTC
When I enter customize mode, the top bar is no longer visible.

This is my bar:

![](http://i.imgur.com/G8u4HXN.png)

And when I go to customize:

![](http://i.imgur.com/QwfKf9T.png)

**Comment by chuckharmston** [comment] 2016-05-11 07:23
Huh, this is fascinating, I've not seen anything like this.

@Noitidart do you see any related tracebacks in the [browser toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox)? Are there any other extensions installed that might be interfering here? Most notably, it seems that you have Tab Center installed, which has [had some issues](https://github.com/bwinton/VerticalTabs/issues/50) with the customize view previously.

**Comment by Noitidart** [comment] 2016-05-11 07:25
Hey Chuck! :)

I have Puzzle Bars installed - https://addons.mozilla.org/en-US/firefox/addon/puzzle-toolbars/

I use it because I like to place the status bar in my URL bar. Like in that above screenshot, I have adblock plus icon in url bar.

**Comment by jaredhirsch** [comment] 2016-05-12 18:15
@Noitidart Thanks for the bug report! Looks from your screenshot like you've got Tab Center installed. There's a known issue where Tab Center breaks `CustomizationUI`, but that's the module this add-on uses to restore the search bar when uninstalling.

Closing as a duplicate of #216, related to bwinton/VerticalTabs#50.

**Closed as completed by jaredhirsch** 2016-05-12 18:15 UTC
