### ISSUE TITLE
Two items can be simultaneously highlighted

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#82] opened 2016-03-11 18:58 UTC
![edd49a4e-e767-11e5-88fa-9bae2645a788](https://cloud.githubusercontent.com/assets/23885/13712364/7a80589e-e780-11e5-9b4b-a4eec5e5d6d9.png)

This is tricky to reproduce, but typing very quickly seems to do so somewhat regularly.

**Comment by jaredhirsch** [comment] 2016-03-14 19:36
I think the underlying issue here is that our Mutation Observer currently only listens for changes in the `url` attribute on child elements of the richlistbox. The full list of mutation events is extremely verbose, so it's a bit tricky to pick just the mutations we really care about.

To detect highlight changes in cases where there are only search suggestions, or in cases where the entire popup clears itself, then pulls in a bunch of new results, we need to listen for other DOM mutations, maybe changes in the number of children, as well as changes in whatever the attribute is that contains the search suggestions.

**Comment by jaredhirsch** [comment] 2016-04-01 20:44
I can't reproduce this any longer. Closing. Let's reopen if it recurs.

**Closed as completed by jaredhirsch** 2016-04-01 20:44 UTC
Labels: size:small
