### ISSUE TITLE
When pressing Ctrl-K (⌘-K), the current tab is used

### ISSUE THREAD

**Issue by orens** [mozilla/universal-search#243] opened 2016-05-30 13:59 UTC
In Firefox, pressing ⌘-K moves the cursor to the search engines box.
Since, with this add-on, search engine box does not exist, I assumed it brings me to the awesome-bar. Instead, I am transferred to Firefox default home (google search).

The _really_ annoying part is that the search page is loaded in the current tab, and, while beforehand I could use ⌘-K without having to open a new tab or worry I may loose my current tab, I can't anymore.

Could you please change ⌘-K to move to the awesome-bar? or at lease make the search in a new tab...

**Comment by chuckharmston** [comment] 2016-07-06 15:57
Thanks for the report!

Closing as a duplicate of https://github.com/mozilla/universal-search/issues/197

**Closed as completed by chuckharmston** 2016-07-06 15:57 UTC
