### ISSUE TITLE
Plugins dysfuctioning after disabling Universal Search experiment add-on

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#221] opened 2016-05-13 15:53 UTC
Reported by @xbouroseu via https://github.com/mozilla/testpilot/issues/840:

> It seems when i disable [the Universal Search] add-on then some plugins did not work (ex. Lastpass, Pocket) and also the "Customize" option from the toolbar brought an empty page (with not tools or whatsoever).
> 
> OS: Mac OS X El Capitan
> Latest Firefox 46.0.1 Release channel

Apparently a browser restart resolved the issue, and after some testing the only experiment responsible for this issue was the "Universal Search Bar" (per https://github.com/mozilla/testpilot/issues/840#issuecomment-219069187)

**Comment by jaredhirsch** [comment] 2016-05-13 17:22
@pdehaan Any time you see a bug report with Customize mode broken, the root cause is https://github.com/bwinton/VerticalTabs/issues/50. Would you mind moving this bug over there?

**Comment by pdehaan** [comment] 2016-05-13 18:34
@6a68 It seems like we should leave the issue open here, since the first half of the bug says that we may be breaking some other add-ons, such as LastPass and Pocket.

But yeah, I think we can ignore the Customize portion since it's adequately covered by https://github.com/bwinton/VerticalTabs/issues/50

**Comment by xbouroseu** [comment] 2016-05-13 20:04
Original bug reporter here: As i originally stated, the problem for me arises when i disable "Universal Search Bar" whether "Tab Center" is activated or not. Nothing of the above happens when i disable "Tab Center". Also, an additional issue as of now is that it does not open the menu at all.

EDIT: Also regarding [bwinton/VerticalTabs#50](url), for me the "Customize page" error was not the same. In my case it had nothing written at all (completetly blank). Also, when i pressed the "exit" button it did not work.

While this is easily fixed by restarting the browser, i too feel that the issue should remain open until it is properly addressed.

**Comment by jaredhirsch** [comment] 2016-05-20 18:35
@xbouroseu Hi! I'd be curious if you could reproduce any of these problems after removing tab center and restarting your browser.

> EDIT: Also regarding bwinton/VerticalTabs#50, for me the "Customize page" error was not the same. In my case it had nothing written at all (completetly blank). Also, when i pressed the "exit" button it did not work.

If you had any problems at all with the customize screen, then many addons will not work properly, because the addons and the customize screen rely on the same underlying code to make reversible changes to Firefox's UI.

The root cause is very likely https://github.com/bwinton/VerticalTabs/issues/50. Note that a fix has landed for the Tab Center bug, so this issue should go away after the next update (next week).

@pdehaan I'm going to close this bug, but if you can reproduce problems with LastPass or Pocket without Tab Center installed, please reopen or open a new bug.

**Closed as completed by jaredhirsch** 2016-05-20 18:35 UTC

**Comment by xbouroseu** [comment] 2016-05-20 19:44
@6a68 Affirmative, i was able to reproduce this bug without "Tab Center" installed. Should we leave this open?
