### ISSUE TITLE
In a Private Window the suggestions and recommended sites are not available  

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#280] opened 2016-07-28 13:55 UTC
[Affected versions]:
- Firefox 45 and up
- Universal Search 1.0.8

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Universal Search add-on (v1.0.8) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a new Private Window.
3. Type a keyword in the Awesome Bar (e.g. wikipedia).
4. Observe the dropdown list with suggestions and recommendations.

[Expected result]:
- The dropdown list displays one recommended site and several suggestions for the written keyword.

[Actual result]:
- The dropdown list displays only the already visited sites.

[Notes]:
- I compared this behavior with the one from the search bar and the suggestions were displayed.
- A screen recording describing the issue was attached.
- [Link](https://drive.google.com/open?id=0B70KzYmGg491bmtKc3VPQzZWbVU) for the screen recording that describes the issue.

**Comment by jaredhirsch** [comment] 2016-09-08 23:02
Working as intended: we don't want to send keystrokes to the server if you're in a private browsing window. Closing.

**Closed as completed by jaredhirsch** 2016-09-08 23:02 UTC
