### ISSUE TITLE
The hover highlight color on Windows 7 makes the recommendation text hardly visible 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#318] opened 2016-10-03 15:01 UTC
[Affected versions]:
- Firefox 48 and up
- Universal Search 1.0.10 (build date 10.03.2016)

[Affected Platforms]:
- Windows 7

[Prerequisites]:
- Latest Universal Search add-on (v1.0.10) is installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and type a keyword in the Awesome Bar (eg. wikipedia).
2. Hover the recommended website and observe the text.

[Expected result]:
- The recommendation text is correctly visible.

[Actual result]:
- The recommendation text hardly visible. 

[Notes]
- Screenshot of the issue: 

![recommended website](https://cloud.githubusercontent.com/assets/19226534/19042072/50298092-8993-11e6-8a09-ba37860417ef.png)

**Comment by chuckharmston** [comment] 2016-10-03 15:02
Can you include a screenshot of what a regular selected result looks like?

**Comment by SoftVision-CosminMuntean** [comment] 2016-10-03 15:05
This screen shot was made on Windows 10: 

![good highlight color](https://cloud.githubusercontent.com/assets/19226534/19042267/026e6ede-8994-11e6-8ef4-7b46b3e85d12.png)

**Comment by chuckharmston** [comment] 2016-10-03 15:06
Sorry, I mean a non-recommendation result in Windows 7.

**Comment by SoftVision-CosminMuntean** [comment] 2016-10-03 15:07
![regular](https://cloud.githubusercontent.com/assets/19226534/19042338/483e37e6-8994-11e6-8395-257d24db8de7.png)

**Comment by chuckharmston** [comment] 2016-10-03 15:08
Thanks! Investigating.

**Comment by chuckharmston** [comment] 2016-10-03 16:03
This is a dupe of https://github.com/mozilla/universal-search/issues/98

**Closed as completed by chuckharmston** 2016-10-03 16:03 UTC
