### ISSUE TITLE
Search engines can not be focused and selected from keyboard arrows when there is no recommended site for the entered string

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#300] opened 2016-08-19 15:04 UTC
[Affected versions]:
- Nightly 51.0a1
- Universal Search 1.0.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Universal Search add-on (v1.0.8) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite.
2. Enter a keyword in the Awesome Bar that won't display any recommended website.
3. Using the keyboard arrows, navigate trough the available search engines.

[Expected result]:
- Even if there is no recommended website displayed, the search engines can be focused and selected from keyboard.

[Actual result]:
- Using the "down" arrow key, when you reach the search engines section, only the first can be focused. 
- Using the "up" arrow key, when you reach the search engines section, only the gearwheel can be focused.

[Notes]:
- The search engine or gearwheel remain focused while navigating back to the suggestions.
- Added a screen recording with the issue: https://goo.gl/D5XbpK

**Comment by jaredhirsch** [comment] 2016-08-25 22:09
dupe of #292, closing

**Closed as completed by jaredhirsch** 2016-08-25 22:09 UTC
